# Generated by Django 4.2.5 on 2023-09-20 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.utcnow)),
                ("client_name", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
    ]
